'use client';

import { Inter } from 'next/font/google';
import '/styles/global.css';
import Header from '../components/header';
import { Jua, Do_Hyeon } from 'next/font/google';

import dynamic from 'next/dynamic';
import { usePathname } from 'next/navigation';
import { useState } from 'react';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };
/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/google-font-display */

const jua = Do_Hyeon({
  subsets: ['latin'],
  weight: ['400'],
  style: ['normal'],
});
const Menu = dynamic(() => import('../components/menu'), { ssr: false });
const inter = Inter({ subsets: ['latin'] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = usePathname();
  const [menuToggle, setMenuToggle] = useState(false);
  return (
    <html lang='kr'>
      <head>
        <link
          href='https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200'
          rel='stylesheet'
        />
      </head>
      {path === '/login' || path === '/register' ? (
        <body>
          <div className='w-full flex justify-center h-full bg-white'>
            <div className='w-full'>{children}</div>
          </div>
        </body>
      ) : (
        <body className={`${jua.className} bg-[#141517] text-white flex`}>
          <div className='flex w-full'>
            <div className=''>
              <div className={`flex flex-col fixed`} style={{ zIndex: 3 }}>
                <button
                  className={`flex -mb-1 mt-3 w-full h-full pl-5 pb-5`}
                  onClick={() => {
                    setMenuToggle(!menuToggle);
                    console.log(path);
                  }}
                >
                  <svg
                    width='40'
                    height='40'
                    viewBox='0 0 40 40'
                    fill='none'
                    xmlns='http://www.w3.org/2000/svg'
                    className='fixed'
                  >
                    <g clip-path='url(#clip0_1128_3162)'>
                      <rect
                        x='11'
                        y='13'
                        width='18'
                        height='2'
                        rx='1'
                        fill='currentColor'
                      ></rect>
                      <rect
                        x='11'
                        y='19'
                        width='18'
                        height='2'
                        rx='1'
                        fill='currentColor'
                      ></rect>
                      <rect
                        x='11'
                        y='25'
                        width='18'
                        height='2'
                        rx='1'
                        fill='currentColor'
                      ></rect>
                    </g>
                    <defs>
                      <clipPath id='clip0_1128_3162'>
                        <rect width='40' height='40' rx='6' fill='white'></rect>
                      </clipPath>
                    </defs>
                  </svg>
                </button>
                <Menu menuToggle={menuToggle} />
              </div>
            </div>
            <div className='flex flex-col w-full h-full '>
              <div
                className='fixed w-[96%] bg-[#141517] ml-20'
                style={{ zIndex: 2 }}
              >
                <Header />
              </div>
              <div className='w-full pt-16 flex'>
                <div
                  className={`${menuToggle ? `ml-60` : 'ml-28'} mt-5 w-full`}
                  style={{ zIndex: 1 }}
                >
                  {children}
                </div>
              </div>
              <div
                className={`flex flex-col justify-center ml-5 ${
                  path === '/following' ? 'mt-80' : ''
                }`}
              >
                <div className='border-t border-gray-300 mt-10 mx-auto w-[90%]' />
                <footer className='flex mt-10 justify-center pl-20'>
                  <div className='footer_cell__0vJSU'>
                    <a
                      rel='noreferrer'
                      className='footer_text__t475V'
                      href='https://policy.naver.com/rules/service.html'
                      target='_blank'
                    >
                      네이버 이용약관
                    </a>
                    <a
                      rel='noreferrer'
                      className='footer_text__t475V'
                      href='https://game.naver.com/policy'
                      target='_blank'
                    >
                      네이버 게임 커뮤니티 가이드
                    </a>
                    <a
                      rel='noreferrer'
                      className='footer_text__t475V'
                      href='https://policy.naver.com/rules/privacy.html'
                      target='_blank'
                    >
                      <strong>개인정보 처리방침</strong>
                    </a>
                    <a
                      rel='noreferrer'
                      className='footer_text__t475V'
                      href='https://game.naver.com/lounge/chzzk/home'
                      target='_blank'
                    >
                      치지직 라운지
                    </a>
                  </div>
                  <div className='footer_cell__0vJSU'>
                    <a
                      rel='noreferrer'
                      className='footer_text__t475V'
                      href='https://help.naver.com/alias/contents1/game/game_10.naver'
                      target='_blank'
                    >
                      네이버 게임 고객센터
                    </a>
                    <a
                      rel='noreferrer'
                      className='footer_text__t475V'
                      href='https://www.navercorp.com'
                      target='_blank'
                    >
                      <strong>ⓒ NAVER Corp.</strong>
                    </a>
                  </div>
                </footer>
              </div>
            </div>
          </div>
        </body>
      )}
    </html>
  );
}
