import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '/styles/global.css';
import Header from '../components/header';

import dynamic from 'next/dynamic';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/google-font-display */
const Menu = dynamic(() => import('../components/menu'), { ssr: false });
const inter = Inter({ subsets: ['latin'] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&display=optional"
          rel="stylesheet"
        />
      </head>
      <body className="bg-[#141517] text-white">
        <Header />
        <div className="flex">
          <Menu />
          <div className="w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
